/* configuration.c
   Copyright (C) 2017 Ferdinand Blomqvist

   This program is free software: you can redistribute it and/or modify it
   under the terms of the GNU General Public License version 2 as published by
   the Free Software Foundation.

   This program is distributed in the hope that it will be useful, but WITHOUT
   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
   FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
   more details.

   You should have received a copy of the GNU General Public License along with
   this program. If not, see <http://www.gnu.org/licenses/>.

   Written by Ferdinand Blomqvist. */

#include "dbg.h"
#include "configuration.h"
#include "version.h"
#include <time.h>

#define HASHLINE "##########################################"

static int print_conf_line(FILE* file, struct config* conf);

void util_get_current_time(char* timestr, size_t max, const char* format)
{
    time_t timer = time(NULL);
    struct tm* tm_info = localtime(&timer);
    strftime(timestr, max, format, tm_info);
}

int util_print_genby_and_config(FILE* file, const char* prog_name,
                                const char* tstr, struct version* ver,
                                struct config* conf)
{
    char timestr[32];
    if(!tstr)
    {
        util_get_current_time(timestr, 32, "%Y-%m-%d %H:%M:%S");
        tstr = timestr;
    }

    static const char* formatstr =
        HASHLINE "\n"
        "# Generated by %s (%s)\n"
        "# version %u.%u.%u, at %s\n"
        "# with the following options:\n#\n";
    int rc;
    if(!ver)
        rc = fprintf(file, formatstr, prog_name, PACKAGE_NAME,
                VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH, tstr);
    else
        rc = fprintf(file, formatstr, prog_name, PACKAGE_NAME,
                ver->major, ver->minor, ver->patch, tstr);

    libcheck(rc > 0, "printing error");

    while(conf->name)
        libcheck(print_conf_line(file, conf++) > 0, "print_conf_line failed");

    libcheck(fprintf(file, HASHLINE "\n") > 0, "printing error");
    return 0;

error:
    return -1;
}

static int print_conf_line(FILE* file, struct config* conf)
{
    // Do not print this line if the print_flag is unset
    if(!conf->print_flag)
        return 1;

    int rc;
    switch(conf->type)
    {
        case type_int:
            rc = fprintf(file, "# --%s=%d\n", conf->name, conf->val.i);
            break;
        case type_long:
            rc = fprintf(file, "# --%s=%ld\n", conf->name, conf->val.l);
            break;
        case type_ulong:
            rc = fprintf(file, "# --%s=%lu\n", conf->name, conf->val.u);
            break;
        case type_size:
            rc = fprintf(file, "# --%s=%zu\n", conf->name, conf->val.s);
            break;
        case type_str:
            rc = fprintf(file, "# --%s=%s\n", conf->name, conf->val.str);
            break;
        case type_bool:
            rc = conf->val.b ? fprintf(file, "# --%s\n", conf->name) : 1;
            break;
        default:
            rc = -1;
            break;
    }
    return rc;
}
