/*
 * This file is generated by the gen-cont tool that is a part of the
 * FB_CONTAINERS package.
 */

#include "slist_double.h"

static void SLIST_DOUBLE_NODE_free(SLIST_DOUBLE_NODE* node)
{ free(node); }

SLIST_DOUBLE* SLIST_DOUBLE_alloc(void)
{
    SLIST_DOUBLE* slist = malloc(sizeof(SLIST_DOUBLE));
    if(!slist)
        return NULL;

    slist->first = NULL;
    slist->last = NULL;
    slist->size = 0;
    return slist;
}

void SLIST_DOUBLE_free(SLIST_DOUBLE* slist)
{
    if(!slist) 
        return;

    SLIST_DOUBLE_NODE* node = slist->first;
    while(node)
    {
        SLIST_DOUBLE_NODE* temp = node;
        node = node->next;
        SLIST_DOUBLE_NODE_free(temp);
    }
    free(slist);
}

SLIST_DOUBLE_NODE* SLIST_DOUBLE_push_front(SLIST_DOUBLE* slist, double data)
{
    SLIST_DOUBLE_NODE* node = malloc(sizeof(SLIST_DOUBLE_NODE));
    if(!node)
        return NULL;

    if(!slist->first)
	slist->last = node;

    node->next = slist->first;
    slist->first = node;
    node->data = data;
    slist->size++;
    return node;
}

SLIST_DOUBLE_NODE* SLIST_DOUBLE_push_back(SLIST_DOUBLE* slist, double data)
{
    SLIST_DOUBLE_NODE* node = malloc(sizeof(SLIST_DOUBLE_NODE));
    if(!node)
        return NULL;

    if(!slist->first)
        slist->last = slist->first = node;
    else
    {
        slist->last->next = node;
        slist->last = node;
    }
    node->next = NULL;
    node->data = data;
    slist->size++;
    return node;
}

double SLIST_DOUBLE_pop_front(SLIST_DOUBLE* slist)
{
    double data = slist->first->data;
    SLIST_DOUBLE_NODE* node = slist->first;
    slist->first = slist->first->next;
    if(!slist->first)
	slist->last = NULL;

    SLIST_DOUBLE_NODE_free(node);
    slist->size--;
    return data;
}

